version: '3'

services:
  server:
    build: server
    ports:
      - '3000:3000'
    links:
      - database
    tty: true
    network_mode: bridge
    env_file:
      ./server/.env
  
  database:
    image: mysql:5.6.27
    restart: always
    volumes:
      - ./server/dev-sql:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=honor
    ports:
      - "3307:3306"
    network_mode: bridge
